const WW2Events = [
    { id: 1, year: 1939, title: "Invasi Polandia", lat: 52.0, lon: 19.0, description: "Jerman menginvasi Polandia, menandai dimulainya Perang Dunia II. Invasi ini menyebabkan Inggris dan Prancis menyatakan perang terhadap Jerman. Serangan kilat atau Blitzkrieg mengejutkan pertahanan Polandia.", image: "https://example.com/invasion-poland.jpg", figure: "Adolf Hitler", figureImage: "https://example.com/hitler.jpg" },
    { id: 2, year: 1940, title: "Pertempuran Prancis", lat: 48.8, lon: 2.3, description: "Jerman melancarkan serangan cepat ke Prancis melalui Ardennes, melewati Garis Maginot. Paris jatuh, dan Prancis menyerah dalam waktu enam minggu.", image: "https://example.com/battle-france.jpg", figure: "Charles de Gaulle", figureImage: "https://example.com/de-gaulle.jpg" },
    { id: 3, year: 1940, title: "Pertempuran Britania", lat: 51.5, lon: -0.1, description: "Luftwaffe Jerman melancarkan kampanye udara besar-besaran terhadap Britania, menargetkan lapangan udara dan kota-kota. RAF berhasil mempertahankan Britania, menandai kekalahan besar pertama Jerman.", image: "https://example.com/battle-britain.jpg", figure: "Winston Churchill", figureImage: "https://example.com/churchill.jpg" },
    { id: 4, year: 1941, title: "Operasi Barbarossa", lat: 55.7, lon: 37.6, description: "Jerman melancarkan invasi ke Uni Soviet, membuka Front Timur dan menyebabkan beberapa pertempuran paling mematikan dalam perang.", image: "https://example.com/operation-barbarossa.jpg", figure: "Joseph Stalin", figureImage: "https://example.com/stalin.jpg" },
    { id: 5, year: 1941, title: "Serangan Pearl Harbor", lat: 21.3, lon: -157.8, description: "Jepang melancarkan serangan mendadak ke pangkalan angkatan laut AS di Pearl Harbor, menyebabkan Amerika Serikat secara resmi memasuki Perang Dunia II.", image: "https://example.com/pearl-harbor.jpg", figure: "Franklin D. Roosevelt", figureImage: "https://example.com/roosevelt.jpg" },
    { id: 6, year: 1942, title: "Pertempuran Midway", lat: 28.2, lon: -177.4, description: "Amerika Serikat mengalahkan Jepang dalam pertempuran laut yang menentukan, mengubah arah perang di Pasifik.", image: "https://example.com/midway.jpg", figure: "Chester Nimitz", figureImage: "https://example.com/nimitz.jpg" },
    { id: 7, year: 1943, title: "Pertempuran Stalingrad", lat: 48.7, lon: 44.5, description: "Uni Soviet berhasil menghentikan dan mengalahkan pasukan Jerman dalam pertempuran yang sangat brutal, menjadi titik balik perang di Front Timur.", image: "https://example.com/stalingrad.jpg", figure: "Georgy Zhukov", figureImage: "https://example.com/zhukov.jpg" },
    { id: 8, year: 1944, title: "Pendaratan Normandia (D-Day)", lat: 49.4, lon: -0.9, description: "Pasukan Sekutu mendarat di pantai Normandia, Prancis, dalam serangan besar-besaran untuk membebaskan Eropa dari pendudukan Nazi.", image: "https://example.com/d-day.jpg", figure: "Dwight D. Eisenhower", figureImage: "https://example.com/eisenhower.jpg" },
    { id: 9, year: 1945, title: "Jatuhnya Berlin", lat: 52.5, lon: 13.4, description: "Pasukan Uni Soviet mengepung dan merebut Berlin, menyebabkan Jerman menyerah dan Hitler bunuh diri.", image: "https://example.com/berlin.jpg", figure: "Georgy Zhukov", figureImage: "https://example.com/zhukov.jpg" },
    { id: 10, year: 1945, title: "Pengeboman Hiroshima", lat: 34.4, lon: 132.4, description: "Amerika Serikat menjatuhkan bom atom pertama di Hiroshima, Jepang, menyebabkan kehancuran besar dan mempercepat akhir Perang Dunia II.", image: "https://example.com/hiroshima.jpg", figure: "Harry S. Truman", figureImage: "https://example.com/truman.jpg" }
  ];